#! /bin/sh
# Sourced from https://github.com/credfeto/scripts/blob/main/development/buildtest

RESTORE=0
RULESET_ADJUSTMENT_FILE=

die() {
    printf '\n\033[31m✗\033[0m %s\n' "$*"
    [ "$RESTORE" = "1" ] && git checkout "$RULESET_ADJUSTMENT_FILE"
    exit 1
}

info() {
    printf '\n\033[32m→\033[0m %s\n' "$*"
}

TEST_BENCHMARKS=
TEST_INTEGRATION=
while [ $# -gt 0 ]; do
    key="$1"

  case $key in
    -b|--no-benchmarks)
      TEST_BENCHMARKS="--filter-not-namespace *.BenchMark.Tests --filter-not-namespace *.BenchMark.Tests.*"
      shift
      ;;
    -i|--no-integration)
      TEST_INTEGRATION="--filter-not-namespace *.Integration.Tests --filter-not-namespace *.Integration.Tests.*"
      shift
      ;;
    *)
      shift
      ;;
  esac
done

PACK=0
HAS_PACKED=$(grep -R "<IsPackable>true</IsPackable>" . --include "*.csproj" | head -1)
if [ -n "$HAS_PACKED" ]; then
  PACK=1
fi

SOLUTION=$(find "$PWD" -type f -iname "*.sln" | head -1)
[ -z "$SOLUTION" ] && SOLUTION=$(find "$PWD" -type f -iname "*.slnx" | head -1)
[ -z "$SOLUTION" ] && die "No Solution found in $(pwd)"

SOURCE_DIR=$(dirname "$SOLUTION")
[ -z "$SOURCE_DIR" ] && die "No Solution dir found in $SOURCE_DIR"

[ -f "$SOURCE_DIR/release.rule-settings.json" ] && RULESET_ADJUSTMENT_FILE="$SOURCE_DIR/release.rule-settings.json"

cd "$SOURCE_DIR" || die "Could not change to $SOURCE_DIR"

RULESET_TYPE=
RULESET_FILE=
if [ -f "$SOURCE_DIR/CodeAnalysis.ruleset" ]; then
  RULESET_TYPE=ruleset
  RULESET_FILE="$SOURCE_DIR/CodeAnalysis.ruleset"
fi

if [ -f "$SOURCE_DIR/../.globalconfig" ]; then
  RULESET_TYPE=globalconfig
  RULESET_FILE="$(readlink -f "$SOURCE_DIR/../.globalconfig")"
fi

if [ -n "$RULESET_TYPE" ] && [ -f "$RULESET_ADJUSTMENT_FILE" ]; then
  info "Overriding ${RULESET_FILE} with ${RULESET_ADJUSTMENT_FILE}"
  dotnet code-analysis "$RULESET_TYPE" \
    --ruleset "$RULESET_FILE" \
    --changes "$RULESET_ADJUSTMENT_FILE" || die "Failed to update $RULESET_FILE"
  RESTORE=1
fi

info "Restoring..."
dotnet restore || die "Restore failed"

info "Cleaning..."
dotnet clean "--nowarn:MSB4241" || die "Clean failed"

info "Building..."
dotnet build \
  --warnaserror \
  --configuration Release \
  --no-restore \
  "-p:ApiCompatGenerateSuppressionFile=true" \
  "-p:ContinuousIntegrationBuild=true" \
  "-p:IsProduction=false" \
  "--nowarn:MSB4241" \
  "-p:Optimize=true" \
  "-p:SuppressNETCoreSdkPreviewMessage=true" \
  "-p:Version=0.0.0.1-test" \
  -nodeReuse:False || die "Build failed"

info "Testing..."
# shellcheck disable=SC2086
dotnet test \
  --configuration Release \
  --no-restore \
  --no-build \
  --long-running 10 \
  $TEST_BENCHMARKS \
  $TEST_INTEGRATION \
  --parallel-algorithm aggressive \
  --ignore-exit-code 8 \
  "-p:ApiCompatGenerateSuppressionFile=true" \
  "-p:ContinuousIntegrationBuild=true" \
  "-p:IsProduction=false" \
  "-p:Optimize=true" \
  "-p:SuppressNETCoreSdkPreviewMessage=true" \
  "-p:Version=0.0.0.1-test" \
  || die "Tests failed"

if [ "$PACK" = "1" ]; then
  info "Packing..."
  dotnet pack \
    --warnaserror \
    --configuration Release \
    --no-restore \
    "-p:ApiCompatGenerateSuppressionFile=true" \
    "-p:ContinuousIntegrationBuild=true" \
    "-p:IncludeSymbols=False" \
    "-p:IsProduction=false" \
    "--nowarn:MSB4241" \
    "-p:Optimize=true" \
    "-p:SuppressNETCoreSdkPreviewMessage=true" \
    "-p:Version=0.0.0.1-test" \
    -nodeReuse:False || die "Packing failed"
fi

[ "$RESTORE" = "1" ] && git checkout "$RULESET_ADJUSTMENT_FILE"

printf '\n\033[32m✓\033[0m %s\n' "Completed"
